- name: Finally rebooting T-Pot
  command: shutdown -r now
  async: 1
  poll: 0

- name: Next login options
  debug:
    msg:
    - "*****    SSH Access:"
    - "*****    ssh {{ ansible_user }}@{{ ansible_host }} -p 7014"
    - ""
    - "*****    Web UI:"
    - "*****    https://{{ ansible_host }}:7017"
    - ""
    - "*****    Admin UI:"
    - "*****    https://{{ ansible_host }}:7012"
